import Link from 'next/link'
import Header from '@/components/layout/Header'
import Footer from '@/components/layout/Footer'

export default function PrivacyPage() {
  return (
    <>
      <Header />
      <main className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">Privacy Policy</h1>
        <p className="text-sm text-gray-500 mb-8">Last updated: January 1, 2025</p>

        <div className="space-y-6 text-sm text-gray-700 leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">1. Information We Collect</h2>
            <p>We collect information you provide directly (name, email, address, payment info), information generated by your use of the platform (browsing history, purchase history, search queries), and technical data (IP address, browser type, device info).</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">2. How We Use Your Information</h2>
            <p>We use your information to process orders and payments, personalize your shopping experience, send transactional and promotional emails (with your consent), improve our platform, prevent fraud, and comply with legal obligations.</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">3. Sharing Your Information</h2>
            <p>We share your information with sellers to fulfill orders, payment processors to handle transactions, shipping carriers to deliver packages, and service providers who help us operate the platform. We do not sell your personal data to third parties for marketing purposes.</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">4. Cookies</h2>
            <p>We use cookies and similar technologies to keep you logged in, remember your preferences, analyze platform usage, and deliver relevant ads. You can control cookie settings through your browser, though some features may not work without them.</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">5. Data Security</h2>
            <p>We use industry-standard encryption (TLS/SSL) to protect data in transit and at rest. Payment card data is processed by PCI-DSS compliant payment processors and is never stored on our servers.</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">6. Your Rights</h2>
            <p>Depending on your location, you may have the right to access, correct, or delete your personal data, opt out of marketing communications, and request data portability. To exercise these rights, contact us at <a href="mailto:privacy@shophub.com" className="text-blue-600 hover:underline">privacy@shophub.com</a>.</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">7. Data Retention</h2>
            <p>We retain your data for as long as your account is active or as needed to provide services. You may request deletion of your account and associated data at any time, subject to legal retention requirements.</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">8. Children&apos;s Privacy</h2>
            <p>ShopHub is not directed at children under 13. We do not knowingly collect personal information from children. If you believe a child has provided us with personal data, please contact us immediately.</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">9. Changes to This Policy</h2>
            <p>We may update this policy periodically. We will notify you of significant changes via email or a prominent notice on the platform. Continued use after changes constitutes acceptance.</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">10. Contact Us</h2>
            <p>For privacy-related questions, contact our Data Protection Officer at <a href="mailto:privacy@shophub.com" className="text-blue-600 hover:underline">privacy@shophub.com</a>.</p>
          </section>
        </div>

        <div className="mt-10 pt-6 border-t border-gray-200 flex gap-4 text-sm">
          <Link href="/terms" className="text-blue-600 hover:underline">Terms of Service</Link>
          <Link href="/help" className="text-blue-600 hover:underline">Help Center</Link>
        </div>
      </main>
      <Footer />
    </>
  )
}
